### ISSUE TITLE
Internal decoder does not work without network

### ISSUE THREAD

**Issue by CompuRoot** [brettz9/qr-secret-decoder-ring#1]
As in subject, issue:
Internal decoder does not work without network.

To reproduce an issue:
Navigate to any site with QR code then turn of WiFi, unplug Ethernet cable and try to decode.

Test platform:
Windows 7
Firefox: 36.0.4
URL decoding for internal decoder set to "Convert URLs to text"

**Comment by brettz9** [comment]
Thank you for the report. I am not sure when I may get to this, but I plan to. If you want to expedite things somewhat, you could send me any errors you see in Tools->Web Developer->Browser Console when attempting the QR code decoding. Can you give me a specific site to try with to make sure I am looking at a problematic one--there are different ways in which QR codes can be added, so it would help to be looking at the same one. Thanks again!

**Comment by brettz9** [comment]
I have not been able to replicate this issue except when using the `jpm run` (Mozilla's testing tools) apparently because it does not register a chrome:// URL properly as needed for cross-domain `getImageData`. When installing the XPI add-on normally, it works fine for me.

I'll really need some more information about the QR code you are attempting to test with (as well as the Firefox version you are now using). And yes, your settings would be helpful.

I will close now since I could not replicate, but feel free to add more details here, and I will reopen if you reply and I can replicate.

**Comment by brettz9** [comment]
In switching to the tool using `jpm xpi`, I was able to replicate though I have not yet distributed this version, so your issue may be a different one if you just installed from AMO or from the repository's XPI file. So if you would, please still send me any details on the QR code you are testing with and your settings. I am reopening the issue in order to fix the problem with jpm.

**Comment by brettz9** [comment]
I have now resolved my issue to have it work with the `jpm` tools of Mozilla. But again, feel free to report your issue here with details on the QR code you are using if you are still experiencing the issue.
